version: '3'

services:
  redis:
    image: redis:6.2
    command: ["redis-server"]
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    command: redis-server --appendonly yes ##MySQLとredis-serverの永続化

  db:
    image: mysql:8.0.23
    container_name: api-container
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: sample
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d

  api:
    stdin_open: true
    tty: true
    depends_on:
      - db
    build:
      context: ./m-api/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    volumes:
      - ./m-api:/app
      - bundle_path:/bundle
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      REDIS_URL: redis://redis:6379

  front:
    build:
      context: ./m-front/
      dockerfile: Dockerfile
    volumes:
      - ./m-front/app:/usr/src/app
    command: 'yarn dev'
    ports:
      - "8080:8080"
volumes:
  bundle_path:
  mysql-data:
    driver: local